name: Test tags
on:
  push:
    tags:
      - dev-*
      - tst-*
      - acc-*
      - prd-*

jobs:
  map_tag_job:
    runs-on: ubuntu-latest
    name: A job to map tags
    steps:
      - uses: actions/checkout@v2
      - id: tag-num
        uses: rcaroprese/map_tag@v5
        with:
          tag-name: ${GITHUB_REF#refs/*/}
      - env:
          DEV_ENV: ${{ secrets.DEV_ENV }}
          TST_ENV: ${{ secrets.TST_ENV }}
          ACC_ENV: ${{ secrets.ACC_ENV }}
          PRD_ENV: ${{ secrets.PRD_ENV }}
        run: echo user-id ${{ steps.tag-num.outputs.user-number }}
        shell: bash